import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
const base=process.env.TEST_URL||'http://127.0.0.1:14318';
const secret=readFileSync('deploy/private/admin-access.txt','utf8');
const email=secret.match(/邮箱：(.+)/)[1],password=secret.match(/密码：(.+)/)[1];
const origin='https://karuizawa.art';
const req=(path,options={})=>fetch(base+path,{redirect:'manual',...options});
assert.equal((await req('/api/health')).status,200);
for(const lang of ['zh-Hans','zh-Hant','en','ja'])assert.equal((await req('/?lang='+lang)).status,200);
let r=await req('/manage/applications',{headers:{'x-oai-user-email':email,'x-oai-user-id':'spoof'}});assert.equal(r.status,307);assert.match(r.headers.get('location'),/\/manage\/login/);
r=await req('/api/manage/applications/test/photos/0');assert.equal(r.status,401);
r=await req('/api/auth/login',{method:'POST',headers:{origin:'https://evil.example'},body:new URLSearchParams({email,password})});assert.equal(r.status,403);
r=await req('/api/auth/login',{method:'POST',headers:{origin},body:new URLSearchParams({email,password,return_to:'//evil.example'})});assert.equal(r.status,303);assert.equal(r.headers.get('location'),origin+'/manage/applications');
const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly/i);assert.match(cookie,/Secure/i);assert.match(cookie,/SameSite=strict/i);
const auth={Cookie:cookie.split(';')[0]};
r=await req('/manage/applications',{headers:auth});assert.equal(r.status,200);assert.match(await r.text(),/收到的申请/);
if(process.env.READ_ONLY){console.log('PASS production health, four languages, admin login, spoof/CSRF protection');process.exit(0);}
const visit=()=>req('/api/visits',{method:'POST',headers:{origin,'x-visit-source':'homepage'}}).then(r=>r.json());
const before=await visit(),after=await visit();assert.equal(after.total,before.total+1);assert.equal(after.today,before.today+1);
const id=randomUUID(),payload={id,type:'space',locale:'zh-Hans',name:'Deployment smoke test',email:'deployment-test@example.invalid',message:'Temporary deployment verification only',consent:true,website:'',address:'Test address',location:'Test',category:'别墅',availability:'Test',authority:true};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9f8AAAAASUVORK5CYII=','base64');
const form=new FormData();form.set('application',JSON.stringify(payload));for(const category of ['exterior','interior'])form.append(category,new Blob([png],{type:'image/png'}),category+'.png');
r=await req('/api/applications',{method:'POST',headers:{origin},body:form});assert.equal(r.status,201,await r.clone().text());
r=await req('/api/applications',{method:'POST',headers:{origin},body:form});assert.equal(r.status,200);
r=await req(`/api/manage/applications/${id}/photos/0`);assert.equal(r.status,401);
r=await req(`/api/manage/applications/${id}/photos/0`,{headers:auth});assert.equal(r.status,200);assert.equal(Buffer.from(await r.arrayBuffer()).compare(png),0);assert.match(r.headers.get('cache-control'),/no-store/);
r=await req(`/manage/applications/${id}`,{headers:auth});assert.equal(r.status,200);assert.match(await r.text(),/Test address/);
r=await req('/api/applications',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({...payload,id:randomUUID()})});assert.equal(r.status,400);
writeFileSync('deploy/private/smoke-state.json',JSON.stringify({id,auth,total:after.total}),{mode:0o600});
console.log('PASS isolated forms, photo upload/read/access control, duplicate protection, counters, auth, locales');
